# temporary storage
tmpdir: '/scratch'

# Demux
barcodes: 'workflow/data/PrimerBarcodesOnlyMInusBuffer_P0024_GBA96.fasta'
primers: 'workflow/data/primers_gba_gbap1.fasta'
barcodePreset: 'ASYMMETRIC'
demuxCross: True
minPrimerMatch: 95

# references
reference: 
    fasta: 'reference/human_GRCh38_chr1_only.fasta'
    label: 'GRCh38' 
regions:
    GBA: 'chr1:155234293-155244663'
    GBAP1: 'chr1:155211825-155229534'
annotation:
    clinvar: 'workflow/data/clinvar_fixnames.vcf.gz'
    consequence: 'workflow/data/Homo_sapiens.GRCh38.108.chromosome.1.gff3.gz'

#clustering
subsample: 1000
randomSeed: 42
maxClusteringReads: 500
minClusterFrequency: 0.125
minClusterReads: 10
maxAmpliconSize: 20000
maxUchime: 1

#alignment
alignHiFi: True
