# temporary storage
tmpdir: '/scratch'

# Demux
barcodes: 'reference/Sequel_96_barcodes_v1.fasta'
primers: 'reference/primers_gba_gbap1.fasta'
demuxCross: True
minPrimerMatch: 95

# references
reference: 
    fasta: 'reference/human_GRCh38_no_alt_analysis_set.fasta'
    label: 'GRCh38' 
regions:
    GBA: 'chr1:155234293-155244663'
    GPAP1: 'chr1:155211825-155229534'
#annotation: 'reference/00-All.fixed_chr.vcf.gz'

#clustering
subsample: 1000
randomSeed: 42
maxClusteringReads: 500
minClusterFrequency: 0.1
minClusterReads: 10
maxAmpliconSize: 20000
maxUchime: 1

# variant calling
